name: hexcolor
description: A new flutter plugin project.
version: 0.0.1
author: ggichure
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.ggichure.github.hexcolor
    pluginClass: HexcolorPlugin
