name: hexcolor
description: A flutter plugin for bringing hex colors to dart hexcolorPlugin.
version: 0.0.1
author: ggichure
email: g.gichure@outlook.com
homepage: https://github.com/ggichure/hexcolor

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.ggichure.github.hexcolor
    pluginClass: HexcolorPlugin
